### ISSUE TITLE
Use an Enum instead of a struct.

### ISSUE THREAD

**Issue by 72A12F4E** [bdolewski/SwiftEmailValidator#5]
For namespacing the isValid function, consider making the EmailValidator struct an enum.

Currently, this code compiles but doesn’t make sense

```swift
import SwiftEmailValidator

let foo = EmailValidator()
``` 

https://www.natashatherobot.com/swift-enum-no-cases/

**Comment by bdolewski** [comment]
That's a great tip, thanks! I was concerned about my code because it looked a bit wonky to me as well. Will change this very soon.
